# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-15 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='miles_from_warehouse',
            field=models.IntegerField(null=True),
        ),
    ]
