# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0002_auto_20180415_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='omniapi.Van'),
        ),
    ]
