# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0003_auto_20180415_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='van_car_plate',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='van',
            name='driver_first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
