# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0004_auto_20180416_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cost',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='van',
            name='driver_last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
