# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-16 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0005_auto_20180416_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(null=True),
        ),
    ]
