# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-04-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniapi', '0006_order_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cost',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
